config/routes.rb
Rails.application.routes.draw do
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  get 'passwords/edit'

  get 'schedule/index'

  devise_for :users, :skip => [:registrations], controllers: { passwords: 'my_passwords' }
  root "application#index"
  get "/about_us", to: "application#about_us" , as: "about_us"
  get '/graduates', to: 'graduated#index', as: 'graduated'
  get '/payments-and-donations', to: 'application#payments', as: 'payments'

  get '/contact', to: 'application#contact', as: 'contact'
  get '/inscriptions', to: 'inscriptions#index', as: 'inscriptions'
  post '/inscription/create', to: 'inscriptions#create', as: "inscription_create"
  get '/circulars', to: 'circulars#index', as: 'circulars'    

  post '/contact_us', to: 'application#contact_us', as: 'contact_us'
  get '/contact_us', to: 'application#contact'
  get '/thank-you', to: 'application#thank_you_contact', as: 'thank_you'
  get '/inscriptions/thank-you', to: 'inscriptions#thank_you', as: 'inscriptions_thank_you'


  get 'circular', to: 'circular#index', as: 'ciruclar'
  get '/parents-school', to: 'application#school_parents', as: "school_parents"
  get '/history-and-appretiation-of-arts', to: 'application#history_of_arts', as: "history_of_arts"

  get '/news', to: 'news#index', as: 'news'
  get '/news/search/:term', to: 'news#search', as: 'news_search'
  get '/news/:id', to: 'news#show', as: 'news_show'
  get '/coexistence-manual', to: 'coexistence_manual#index', as: 'coexistence_manual'

  get "schedules", to: "schedules#index", as: "schedules_front"

  get '/faq', to: 'application#faq', as: 'faq'
  
  resource :passwords

  get '/change_locale/:locale', to: 'application#change_locale', as: 'change_locale'
  get "admin", to: "users#index", as: "admin"

  scope :admin do
    get "schedule/", to: "schedules#index_admin", as: "schedules_admin"
    resources :schedules
    get '/users', to: 'users#index', as: 'users'
    post '/users', to: 'users#create', as: 'users_create'
    get '/users/import', to: 'users#index_import', as: 'show_import_user'
    get '/users/new', to: 'users#new', as: 'new_user'
    get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
    get '/users/:id', to: 'users#show', as: 'user'
    patch '/users/:id', to: 'users#update', as: 'update_user'
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: 'destroy_user'
    post '/users/import', to: 'users#import', as: 'import_users'

    get "category_post", to: "category_posts#index_admin", as: "category_posts_admin"
    get "category_posts/new", to: "category_posts#new", as: "new_category_posts"
    get "category_posts/edit/:id", to: "category_posts#edit", as: "edit_category_posts"
    post "category_posts", to: "category_posts#create"
    patch "category_posts/update/:id", to: "category_posts#update", as: "update_category_posts"
    delete "category_posts/:id", to: "category_posts#destroy", as: "destroy_category_posts"

    get "post", to: "posts#index_admin", as: "posts_admin"
    get "posts/new", to: "posts#new", as: "new_posts"
    get "posts/edit/:slug", to: "posts#edit", as: "edit_posts"
    post "posts", to: "posts#create"
    patch "posts/update/:slug", to: "posts#update", as: "update_posts"
    delete "posts/:slug", to: "posts#destroy", as: "destroy_posts"

    get "parents-lesson", to: "parent_lessons#index_admin", as: "parents_school_lessons_admin"
    get "parents-lesson/new", to: "parent_lessons#new", as: "new_parents_school_lessons"
    get "parents-lesson/edit/:id", to: "parent_lessons#edit", as: "edit_parents_school_lessons"
    post "parents-lesson", to: "parent_lessons#create_record"
    patch "parents-lesson/update/:id", to: "parent_lessons#update", as: "update_parents_school_lessons"
    delete "parents-lesson/:id", to: "parent_lessons#destroy", as: "destroy_parents_school_lessons"

    get "history-of-arts-lesson", to: "history_lessons#index_admin", as: "history_lessons_admin"
    get "history-of-arts-lesson/new", to: "history_lessons#new", as: "new_history_lessons"
    get "history-of-arts-lesson/edit/:id", to: "history_lessons#edit", as: "edit_history_lessons"
    post "history-of-arts-lesson", to: "history_lessons#create_record", as: "history_create"
    patch "history-of-arts-lesson/update/:id", to: "history_lessons#update", as: "update_history_lessons"
    delete "history-of-arts-lesson/:id", to: "history_lessons#destroy", as: "destroy_history_lessons"

    get "home_image", to: "home_images#index_admin", as: "home_images_admin"
    get "home_images/new", to: "home_images#new", as: "new_home_images"
    get "home_images/edit/:id", to: "home_images#edit", as: "edit_home_images"
    post "home_images", to: "home_images#create"
    patch "home_images/update/:id", to: "home_images#update", as: "update_home_images"
    delete "home_images/:id", to: "home_images#destroy", as: "destroy_home_images"
    patch "home_images/change_status/:id", to: "home_images#change_status", as: "change_status_home_images"

    #resources :setups
    get 'setup', to: "setups#edit", as: "edit_setup"
    patch 'setup', to: "setups#update", as: "setup_update"
    post 'setup', to: "setups#edit", as: "setup"
    
    get "circulars", to: "circulars#index_admin", as: 'circulars_admin'
    get "circulars/new", to: "circulars#new_admin", as: "create_circular"
    get "circulars/:id/edit", to: "circulars#edit_admin", as: "edit_circular"
    patch "circulars/:id", to: "circulars#update", as: "circulars_update"
    post "circulars", to: "circulars#create", as: "circulars_create"

  end

  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false, unless: "/admin/*path"

end

app/models/home_image.rb
class HomeImage < ApplicationRecord
  resourcify
  
  has_attached_file :image
	validates :image, attachment_presence: false
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/home_images_controller.rb
class HomeImagesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_home_image, only: [:show, :edit, :update, :destroy, :change_status]

  layout 'admin', only: [:index_admin, :new, :edit]
  def index_admin
    @images_active = HomeImage.where(status: true)
    @images_inactive = HomeImage.where(status: false)
  end

  def show
  end

  def new
    @image = HomeImage.new
  end

  def edit
  end

  def create
    @image = HomeImage.new(home_image_params)
    respond_to do |format|
      if @image.save
        format.html { redirect_to home_images_admin_path, notice: 'banner was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(home_image_params)
        format.html { redirect_to home_images_admin_path, notice: 'banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to home_images_admin_path, notice: 'banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_status
    if @image.status
      @image.status = false
    else
      @image.status = true
    end
    @image.save
    respond_to do |format|
      format.html { redirect_to home_images_admin_path, notice: 'banner was successfully updated.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home_image
      @image = HomeImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_image_params
      params.require(:home_image).permit(:image, :status)
    end
end

app/helpers/home_images_helper.rb
module HomeImagesHelper
end

app/views/home_images/edit.html.erb
<div class="col-12 stretch-card">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Editar banner</h3>
      <p class="card-description">
        Ingresa la información que desees modificar
      </p>
      <%= form_with(model: @image, local: true, url: update_home_images_path(@image)) do |form| %>
        <% if @image.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@image.errors.count, "error") %> prohibited this banner from being saved:</h2>

            <ul>
            <% @image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            Banner actual
          </div>
          <div class="col-sm-9">
            <%= image_tag  @image.image.url, class: "img-thumbnail" %>
          </div>
        </div>

        <div class="form-group row" data-toggle="tooltip" title="Dimensiones recomendadas: 1920px x 1080px">
          <%= form.label :image, "Banner", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.file_field :image, class: "form-control", id: "uploader" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :status, "¿Activo?", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9 text-left">
            <%= form.check_box :status, class: "" %>
          </div>
        </div>

        <div class="actions">
          <%= form.submit "Guardar", class: "btn btn-success mr-2" %> <%= link_to 'Cancelar', home_images_admin_path, class: "btn btn-light"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $("#uploader").fileinput({'showUpload':false, 'previewFileType':'any'});
</script>

app/views/home_images/index_admin.html.erb
<div class="row">
  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <a href="<%= new_home_images_path %>" class="btn btn-outline-success mr-2 btn-sm">Nuevo banner</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row index-admin">
  <div class="col-12 grid-margin">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title mb-5">Banners para el home</h1>
        <h4 class="card-title mb-4">Banners activos</h4>
        <div class="table-responsive mb-4">
          <table class="table center-aligned-table">
            <thead>
              <tr>
                <th class="border-bottom-0">Banner</th>
                <th class="border-bottom-0"></th>
              </tr>
            </thead>
            <tbody>
            <% @images_active.each do |image| %>
              <tr>
                <td><%= image_tag image.image.url, class: "img-thumbnail" %></td>
                <td>
                  <a href="<%= edit_home_images_path(image) %>" class="btn btn-outline-success btn-sm mr-2">Editar</a>
                  <%= link_to 'Eliminar', destroy_home_images_path(image),  data: {:confirm => '¿Estás seguro?'}, :method => :delete, class: "btn btn-outline-danger btn-sm mr-2" %>
                  <%= link_to 'Desactivar', change_status_home_images_path(image),  data: {:confirm => '¿Estás seguro?'}, :method => :patch, class: "btn btn-outline-info btn-sm" %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

        <h4 class="card-title mb-4">Banners inactivos</h4>
        <div class="table-responsive">
          <table class="table center-aligned-table">
            <thead>
              <tr>
                <th class="border-bottom-0">Banner</th>
                <th class="border-bottom-0"></th>
              </tr>
            </thead>
            <tbody>
            <% @images_inactive.each do |image| %>
              <tr>
                <td><%= image_tag image.image.url, class: "img-thumbnail"  %></td>
                <td>
                  <a href="<%= edit_home_images_path(image) %>" class="btn btn-outline-success btn-sm mr-2">Editar</a>
                  <%= link_to 'Eliminar', destroy_home_images_path(image),  data: {:confirm => '¿Estás seguro?'}, :method => :delete, class: "btn btn-outline-danger btn-sm mr-2" %>
                  <%= link_to 'Activar', change_status_home_images_path(image),  data: {:confirm => '¿Estás seguro?'}, :method => :patch, class: "btn btn-outline-info btn-sm" %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home_images/new.html.erb
<div class="col-12 stretch-card">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Nuevo banner</h3>
      <p class="card-description">
        Ingresa la información
      </p>
      <%= form_with(model: @image, local: true, url: '/admin/home_images') do |form| %>
        <% if @image.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@image.errors.count, "error") %> prohibited this banner from being saved:</h2>

            <ul>
            <% @image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group row" data-toggle="tooltip" title="Dimensiones recomendadas: 1920px x 1080px">
          <%= form.label :image, "Banner", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.file_field :image, class: "form-control", id: "uploader" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :status, "¿Activo?", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9 text-left">
            <%= form.check_box :status, class: "" %>
          </div>
        </div>

        <div class="actions">
          <%= form.submit "Guardar", class: "btn btn-success mr-2" %> <%= link_to 'Cancelar', home_images_admin_path, class: "btn btn-light"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $("#uploader").fileinput({'showUpload':false, 'previewFileType':'any'});
</script>