config/routes.rb
Rails.application.routes.draw do
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  get 'passwords/edit'

  get 'schedule/index'

  devise_for :users, :skip => [:registrations], controllers: { passwords: 'my_passwords' }
  root "application#index"
  get "/about_us", to: "application#about_us" , as: "about_us"
  get '/graduates', to: 'graduated#index', as: 'graduated'
  get '/payments-and-donations', to: 'application#payments', as: 'payments'

  get '/contact', to: 'application#contact', as: 'contact'
  get '/inscriptions', to: 'inscriptions#index', as: 'inscriptions'
  post '/inscription/create', to: 'inscriptions#create', as: "inscription_create"
  get '/circulars', to: 'circulars#index', as: 'circulars'    

  post '/contact_us', to: 'application#contact_us', as: 'contact_us'
  get '/contact_us', to: 'application#contact'
  get '/thank-you', to: 'application#thank_you_contact', as: 'thank_you'
  get '/inscriptions/thank-you', to: 'inscriptions#thank_you', as: 'inscriptions_thank_you'


  get 'circular', to: 'circular#index', as: 'ciruclar'
  get '/parents-school', to: 'application#school_parents', as: "school_parents"
  get '/history-and-appretiation-of-arts', to: 'application#history_of_arts', as: "history_of_arts"

  get '/news', to: 'news#index', as: 'news'
  get '/news/search/:term', to: 'news#search', as: 'news_search'
  get '/news/:id', to: 'news#show', as: 'news_show'
  get '/coexistence-manual', to: 'coexistence_manual#index', as: 'coexistence_manual'

  get "schedules", to: "schedules#index", as: "schedules_front"

  get '/faq', to: 'application#faq', as: 'faq'
  
  resource :passwords

  get '/change_locale/:locale', to: 'application#change_locale', as: 'change_locale'
  get "admin", to: "users#index", as: "admin"

  scope :admin do
    get "schedule/", to: "schedules#index_admin", as: "schedules_admin"
    resources :schedules
    get '/users', to: 'users#index', as: 'users'
    post '/users', to: 'users#create', as: 'users_create'
    get '/users/import', to: 'users#index_import', as: 'show_import_user'
    get '/users/new', to: 'users#new', as: 'new_user'
    get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
    get '/users/:id', to: 'users#show', as: 'user'
    patch '/users/:id', to: 'users#update', as: 'update_user'
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: 'destroy_user'
    post '/users/import', to: 'users#import', as: 'import_users'

    get "category_post", to: "category_posts#index_admin", as: "category_posts_admin"
    get "category_posts/new", to: "category_posts#new", as: "new_category_posts"
    get "category_posts/edit/:id", to: "category_posts#edit", as: "edit_category_posts"
    post "category_posts", to: "category_posts#create"
    patch "category_posts/update/:id", to: "category_posts#update", as: "update_category_posts"
    delete "category_posts/:id", to: "category_posts#destroy", as: "destroy_category_posts"

    get "post", to: "posts#index_admin", as: "posts_admin"
    get "posts/new", to: "posts#new", as: "new_posts"
    get "posts/edit/:slug", to: "posts#edit", as: "edit_posts"
    post "posts", to: "posts#create"
    patch "posts/update/:slug", to: "posts#update", as: "update_posts"
    delete "posts/:slug", to: "posts#destroy", as: "destroy_posts"

    get "parents-lesson", to: "parent_lessons#index_admin", as: "parents_school_lessons_admin"
    get "parents-lesson/new", to: "parent_lessons#new", as: "new_parents_school_lessons"
    get "parents-lesson/edit/:id", to: "parent_lessons#edit", as: "edit_parents_school_lessons"
    post "parents-lesson", to: "parent_lessons#create_record"
    patch "parents-lesson/update/:id", to: "parent_lessons#update", as: "update_parents_school_lessons"
    delete "parents-lesson/:id", to: "parent_lessons#destroy", as: "destroy_parents_school_lessons"

    get "history-of-arts-lesson", to: "history_lessons#index_admin", as: "history_lessons_admin"
    get "history-of-arts-lesson/new", to: "history_lessons#new", as: "new_history_lessons"
    get "history-of-arts-lesson/edit/:id", to: "history_lessons#edit", as: "edit_history_lessons"
    post "history-of-arts-lesson", to: "history_lessons#create_record", as: "history_create"
    patch "history-of-arts-lesson/update/:id", to: "history_lessons#update", as: "update_history_lessons"
    delete "history-of-arts-lesson/:id", to: "history_lessons#destroy", as: "destroy_history_lessons"

    get "home_image", to: "home_images#index_admin", as: "home_images_admin"
    get "home_images/new", to: "home_images#new", as: "new_home_images"
    get "home_images/edit/:id", to: "home_images#edit", as: "edit_home_images"
    post "home_images", to: "home_images#create"
    patch "home_images/update/:id", to: "home_images#update", as: "update_home_images"
    delete "home_images/:id", to: "home_images#destroy", as: "destroy_home_images"
    patch "home_images/change_status/:id", to: "home_images#change_status", as: "change_status_home_images"

    #resources :setups
    get 'setup', to: "setups#edit", as: "edit_setup"
    patch 'setup', to: "setups#update", as: "setup_update"
    post 'setup', to: "setups#edit", as: "setup"
    
    get "circulars", to: "circulars#index_admin", as: 'circulars_admin'
    get "circulars/new", to: "circulars#new_admin", as: "create_circular"
    get "circulars/:id/edit", to: "circulars#edit_admin", as: "edit_circular"
    patch "circulars/:id", to: "circulars#update", as: "circulars_update"
    post "circulars", to: "circulars#create", as: "circulars_create"

  end

  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false, unless: "/admin/*path"

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  require 'csv'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 1..128
  def self.import(file)
    puts "*****************"
    puts "*****************"
    puts "*****************"
    pp file
    puts "*****************"
    puts "*****************"
    puts "*****************"
    puts "*****************"
    pp File.read(file.path).encoding
    puts "*****************"
    puts "*****************"
    puts "*****************"
    CSV.foreach(file.path, :headers => true, :encoding => 'ISO-8859-1', :col_sep => ",") do |row|
      user_hash = row.to_hash
      puts "*****************"
      puts "-------- Usuario --------"
      puts "*****************"
      pp user_hash
      @user = User.new(user_hash)
      @user.email = @user.email.strip unless @user.email.nil?
      @user.password = @user.password.strip unless @user.password.nil?
      @user.password_confirmation = @user.password_confirmation.strip unless @user.password_confirmation.nil?
      @user.save
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

    require 'csv'
    layout 'admin', only: [:index, :new, :edit, :show, :index_import]
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    
    # GET /tests
    # GET /tests.json
    def index
        unless current_user.has_role? :admin
            redirect_to root_path
        end
        @users = User.all
        puts "*******"
        puts @users
    end
    
    # GET /tests/1
    # GET /tests/1.json
    def show
    end
    
    # GET /tests/new
    def new
        @user = User.new
    end
    
    # GET /tests/1/edit
    def edit
    end
    
    # POST /tests
    # POST /tests.json
    def create
        @user = User.new(user_params)
        
        respond_to do |format|
            if @user.save
                format.html { redirect_to @user, notice: 'User was successfully created.' }
                format.json { render action: 'show', status: :created, location: @user }
            else
                format.html { render action: 'new' }
                format.json { render json: @test.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # PATCH/PUT /tests/1
    # PATCH/PUT /tests/1.json
    def update
        respond_to do |format|
            user_req = nil
            if user_params[:password].blank?
                user_req = @user.update_without_password(user_params)
            else
                user_req = @user.update(user_params)
            end
            if user_req
                format.html { redirect_to @user, notice: 'User was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: 'edit' }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /tests/1
    # DELETE /tests/1.json
    def destroy
        @user.destroy
        respond_to do |format|
            format.html { redirect_to users_url }
            format.json { head :no_content }
        end
    end

    def index_import
    end

    def import
        User.import(params[:file])
        redirect_to users_path, notice: "imported correctly"
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
        def set_user
            @user = User.find(params[:id])
        end
        
        # Never trust parameters from the scary internet, only allow the white list through.
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, url: url, id: 'circular-form', method: method  do |f| %>
    <div class="form-group">
        <label for="exampleInputEmail1">Nombre</label>
        <%= f.text_field :name, placeholder: 'Nombre', class: 'form-control', required: true %>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <%= f.text_field :email, placeholder: 'Email', class: 'form-control', required: true %>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Contraseña</label>
        <%= f.password_field :password, placeholder: 'Contraseña', class: 'form-control', required: required_pass %>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Confirme Contraseña</label>
        <%= f.password_field :password_confirmation, placeholder: 'Confirme Contraseña', class: 'form-control', required: required_pass %>
    </div>
    <%= f.submit button_text, class: 'btn btn-success mr-2', type: 'submit' %>
    <%= submit_tag("Limpiar", { :name => 'reset', :id => 'reset_button', :type => "reset", :class => 'btn btn-light' }) %>
<% end %>

app/views/users/_layout_form.html.erb
<div class="row">
    <div class="col-12 col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <%= link_to users_path do %>
                    <button type="button" class="btn btn-back btn-icons btn-rounded btn-light">
                        <i class="fa fa-arrow-left"></i>
                    </button>
                <% end %>
                <%= yield %>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<%= render :layout => 'layout_form' do %>
    <h4 class="card-title">Editar usuario</h4>
    <%= render "form", circular: @circular, url: update_user_path, method: 'patch', button_text: 'Editar', required_pass: false  %>
<% end %>

app/views/users/index.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<div class="row">
    <div class="col-12 col-md-7 col-lg-7 col-xl-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body text-center">
                <div class="d-flex flex-wrap">
                    <%= link_to new_user_path  do%>
                    <button class="btn btn-info m-2 my-md-0">
                        Crear usuario
                    </button>
                    <% end %>
                    <%= link_to show_import_user_path  do%>
                    <button class="btn btn-info m-2 my-md-0">
                        Importar usuarios
                    </button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Listado de usuarios</h4>
                <div class="table-responsive">
                    <table id="table-users" class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Email</th>
                                <th class="text-center">Mostrar</th>
                                <th class="text-center">Editar</th>
                                <th class="text-center">Borrar</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% if @users.length > 0 %>
                                <% @users.each_with_index do |user, index| %>
                                <tr>
                                    <td><%= indexplus = index + 1 %></td>
                                    <td><%= user.name %></td>
                                    <td><%= user.email %></td>
                                    <td class="text-center">
                                        <%= link_to user do%>
                                            <%= fa_icon "eye" %>
                                        <% end %>
                                    </td>
                                    <td class="text-center">
                                        <%= link_to edit_user_path(user) do%>
                                            <%= fa_icon "edit" %>
                                        <% end %>
                                    </td>
                                    <td class="text-center">
                                        <%= link_to user, :method => :delete, data: { confirm: 'Estas seguro?' } do %>
                                            <%= fa_icon "trash-o" %>
                                        <% end %>
                                    </td>
                                </tr>
                                <% end %>
                            <% else %>
                            <tr>
                                <td colspan="8" class="text-center text-info">
                                    <h3 class="mt-4">
                                        No hay usuarios creados en este momento
                                    </h3>
                                    <%= link_to new_user_path do%>
                                    <button class="btn btn-success">
                                        Crear
                                    </button>
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
    
            </div>
        </div>
    </div>
</div>

<script>
  $(document).ready( function () {
    $('#table-users').DataTable({
      "language": {
          "url": "https://cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
      }
    });
  } );
</script>

app/views/users/index_import.html.erb
<%= render :layout => 'layout_form' do %>
    <h4 class="card-title">Importar usuarios</h4>
    <p class="text-info">
        Archivo csv separado por comas con cabecera name,email,password,password_confirmation
    </p>
    <%= form_tag import_users_path, multipart: true  do%>
        <div class="form-group">
            <%= file_field_tag :file, id: "inputImport", class: "form-control-file", required: true %>
            <%= submit_tag "Import", class: "btn btn-success mr-2 mt-4"  %>
        </div>
    <% end %>
<% end %>

app/views/users/new.html.erb
<%= render :layout => 'layout_form' do %>
    <h4 class="card-title">Nuevo usuario</h4>
    <%= render "form", user: @user, url: users_create_path, method: 'post', button_text: 'Crear', required_pass: true %>
<% end %>

app/views/users/show.html.erb
<%= render :layout => 'layout_form' do %>
    <p>
        <%= @user.name %>
    </p>
    <p>
        Email: <%= @user.email %>
    </p>
    <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>