config/routes.rb
Rails.application.routes.draw do
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  get 'passwords/edit'

  get 'schedule/index'

  devise_for :users, :skip => [:registrations], controllers: { passwords: 'my_passwords' }
  root "application#index"
  get "/about_us", to: "application#about_us" , as: "about_us"
  get '/graduates', to: 'graduated#index', as: 'graduated'
  get '/payments-and-donations', to: 'application#payments', as: 'payments'

  get '/contact', to: 'application#contact', as: 'contact'
  get '/inscriptions', to: 'inscriptions#index', as: 'inscriptions'
  post '/inscription/create', to: 'inscriptions#create', as: "inscription_create"
  get '/circulars', to: 'circulars#index', as: 'circulars'    

  post '/contact_us', to: 'application#contact_us', as: 'contact_us'
  get '/contact_us', to: 'application#contact'
  get '/thank-you', to: 'application#thank_you_contact', as: 'thank_you'
  get '/inscriptions/thank-you', to: 'inscriptions#thank_you', as: 'inscriptions_thank_you'


  get 'circular', to: 'circular#index', as: 'ciruclar'
  get '/parents-school', to: 'application#school_parents', as: "school_parents"
  get '/history-and-appretiation-of-arts', to: 'application#history_of_arts', as: "history_of_arts"

  get '/news', to: 'news#index', as: 'news'
  get '/news/search/:term', to: 'news#search', as: 'news_search'
  get '/news/:id', to: 'news#show', as: 'news_show'
  get '/coexistence-manual', to: 'coexistence_manual#index', as: 'coexistence_manual'

  get "schedules", to: "schedules#index", as: "schedules_front"

  get '/faq', to: 'application#faq', as: 'faq'
  
  resource :passwords

  get '/change_locale/:locale', to: 'application#change_locale', as: 'change_locale'
  get "admin", to: "users#index", as: "admin"

  scope :admin do
    get "schedule/", to: "schedules#index_admin", as: "schedules_admin"
    resources :schedules
    get '/users', to: 'users#index', as: 'users'
    post '/users', to: 'users#create', as: 'users_create'
    get '/users/import', to: 'users#index_import', as: 'show_import_user'
    get '/users/new', to: 'users#new', as: 'new_user'
    get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
    get '/users/:id', to: 'users#show', as: 'user'
    patch '/users/:id', to: 'users#update', as: 'update_user'
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: 'destroy_user'
    post '/users/import', to: 'users#import', as: 'import_users'

    get "category_post", to: "category_posts#index_admin", as: "category_posts_admin"
    get "category_posts/new", to: "category_posts#new", as: "new_category_posts"
    get "category_posts/edit/:id", to: "category_posts#edit", as: "edit_category_posts"
    post "category_posts", to: "category_posts#create"
    patch "category_posts/update/:id", to: "category_posts#update", as: "update_category_posts"
    delete "category_posts/:id", to: "category_posts#destroy", as: "destroy_category_posts"

    get "post", to: "posts#index_admin", as: "posts_admin"
    get "posts/new", to: "posts#new", as: "new_posts"
    get "posts/edit/:slug", to: "posts#edit", as: "edit_posts"
    post "posts", to: "posts#create"
    patch "posts/update/:slug", to: "posts#update", as: "update_posts"
    delete "posts/:slug", to: "posts#destroy", as: "destroy_posts"

    get "parents-lesson", to: "parent_lessons#index_admin", as: "parents_school_lessons_admin"
    get "parents-lesson/new", to: "parent_lessons#new", as: "new_parents_school_lessons"
    get "parents-lesson/edit/:id", to: "parent_lessons#edit", as: "edit_parents_school_lessons"
    post "parents-lesson", to: "parent_lessons#create_record"
    patch "parents-lesson/update/:id", to: "parent_lessons#update", as: "update_parents_school_lessons"
    delete "parents-lesson/:id", to: "parent_lessons#destroy", as: "destroy_parents_school_lessons"

    get "history-of-arts-lesson", to: "history_lessons#index_admin", as: "history_lessons_admin"
    get "history-of-arts-lesson/new", to: "history_lessons#new", as: "new_history_lessons"
    get "history-of-arts-lesson/edit/:id", to: "history_lessons#edit", as: "edit_history_lessons"
    post "history-of-arts-lesson", to: "history_lessons#create_record", as: "history_create"
    patch "history-of-arts-lesson/update/:id", to: "history_lessons#update", as: "update_history_lessons"
    delete "history-of-arts-lesson/:id", to: "history_lessons#destroy", as: "destroy_history_lessons"

    get "home_image", to: "home_images#index_admin", as: "home_images_admin"
    get "home_images/new", to: "home_images#new", as: "new_home_images"
    get "home_images/edit/:id", to: "home_images#edit", as: "edit_home_images"
    post "home_images", to: "home_images#create"
    patch "home_images/update/:id", to: "home_images#update", as: "update_home_images"
    delete "home_images/:id", to: "home_images#destroy", as: "destroy_home_images"
    patch "home_images/change_status/:id", to: "home_images#change_status", as: "change_status_home_images"

    #resources :setups
    get 'setup', to: "setups#edit", as: "edit_setup"
    patch 'setup', to: "setups#update", as: "setup_update"
    post 'setup', to: "setups#edit", as: "setup"
    
    get "circulars", to: "circulars#index_admin", as: 'circulars_admin'
    get "circulars/new", to: "circulars#new_admin", as: "create_circular"
    get "circulars/:id/edit", to: "circulars#edit_admin", as: "edit_circular"
    patch "circulars/:id", to: "circulars#update", as: "circulars_update"
    post "circulars", to: "circulars#create", as: "circulars_create"

  end

  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false, unless: "/admin/*path"

end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  resourcify
  
  has_attached_file :image
	validates :image, attachment_presence: false
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  
  belongs_to :category_post
  
  def self.search(term)
    if term
      where('lower(title) LIKE ?', "%#{term.downcase}%").order(created_at: :desc)
    else
      all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  layout 'admin', only: [:index_admin, :new, :edit]
  def index_admin
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
    @categories = CategoryPost.all
  end

  def edit
    @categories = CategoryPost.all
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_admin_path, notice: 'post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_admin_path, notice: 'post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_admin_path, notice: 'post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :content, :image, :category_post_id, :title_en, :content_en)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="col-12 stretch-card">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Editar evento</h3>
      <p class="card-description">
        Ingresa la información que desees modificar
      </p>
      <%= form_with(model: @post, local: true, url: update_posts_path(@post)) do |form| %>
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group row">
          <%= form.label :title, "Titulo (Español)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_field :title, class: "form-control", placeholder: "Ej: Inicio de clases" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :title_en, "Titulo (Inglés)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_field :title_en, class: "form-control", placeholder: "Ej: Inicio de clases" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :author, "Autor", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_field :author, class: "form-control", placeholder: "Ej: Maria Carvajal" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :content, "Contenido (español)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_area :content, class: "form-control", id: "editor" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :content_en, "Contenido (Inglés)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_area :content_en, class: "form-control", id: "editor-2" %>
          </div>
        </div>

        <div class="form-group row" data-toggle="tooltip" title="Dimensiones recomendadas: 650px x 450px">
          <%= form.label :image, "Imagen principal", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.file_field :image, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :category_post_id, "Categoría", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.select :category_post_id, @categories.collect{|c| [c.name, c.id]}, {:include_blank => 'Seleccione...'}, {class: 'form-control', required: true} %>
          </div>
        </div>

        <div class="actions">
          <%= form.submit "Guardar", class: "btn btn-success mr-2" %> <%= link_to 'Cancelar', posts_admin_path, class: "btn btn-light"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  CKEDITOR.replace( 'editor-2' );
</script>

app/views/posts/index_admin.html.erb
<div class="row">
  <div class="col-12 col-md-8 col-lg-7 col-xl-5 grid-margin stretch-card">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <a href="<%= new_posts_path %>" class="btn btn-outline-success m-2 my-md-0 btn-sm">Nueva noticia</a>
            <a href="<%= category_posts_admin_path %>" class="btn btn-outline-info m-2 my-md-0 btn-sm">Editar categorias</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12 grid-margin">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title mb-5">Noticias</h5>
        <div class="table-responsive">
          <table class="table center-aligned-table">
            <thead>
              <tr>
                <th class="border-bottom-0">Titulo</th>
                <th class="border-bottom-0">Contenido</th>
                <th class="border-bottom-0">Autor</th>
                <th class="border-bottom-0">Categoría</th>
                <th class="border-bottom-0">Fecha de publicación</th>
                <th class="border-bottom-0"></th>
              </tr>
            </thead>
            <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= strip_tags post.content.truncate(100) %></td>
                <td><%= post.author %></td>
                <td><%= post.category_post.name %></td>
                <td><%= post.created_at.strftime("%F") %></td>
                <td>
                  <a href="<%= edit_posts_path(post) %>" class="btn btn-outline-success btn-sm mr-2">Editar</a>
                  <%= link_to 'Eliminar', destroy_posts_path(post),  data: {:confirm => '¿Estás seguro?'}, :method => :delete, class: "btn btn-outline-danger btn-sm" %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-12 stretch-card">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Nueva noticia</h3>
      <p class="card-description">
        Ingresa la información
      </p>
      <%= form_with(model: @post, local: true, url: '/admin/posts') do |form| %>
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group row">
          <%= form.label :title, "Titulo (Español)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_field :title, class: "form-control", placeholder: "Ej: Inicio de clases" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :title_en, "Titulo (Inglés)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_field :title_en, class: "form-control", placeholder: "Ej: Inicio de clases" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :author, "Autor", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_field :author, class: "form-control", placeholder: "Ej: Maria Carvajal" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :content, "Contenido (Español)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_area :content, class: "form-control", id: "editor" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :content_en, "Contenido (Inglés)", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.text_area :content_en, class: "form-control", id: "editor-2" %>
          </div>
        </div>

        <div class="form-group row" data-toggle="tooltip" title="Dimensiones recomendadas: 650px x 450px">
          <%= form.label :image, "Imagen principal", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.file_field :image, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :category_post_id, "Categoría", class: "col-sm-3 col-form-label" %>
          <div class="col-sm-9">
            <%= form.select :category_post_id, @categories.collect{|c| [c.name, c.id]},  {:include_blank => 'Seleccione...'}, {class: 'form-control', required: true} %>
          </div>
        </div>

        <div class="actions">
          <%= form.submit "Guardar", class: "btn btn-success mr-2" %> <%= link_to 'Cancelar', posts_admin_path, class: "btn btn-light"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  CKEDITOR.replace( 'editor-2' );
</script>