config/routes.rb
Rails.application.routes.draw do
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  get 'passwords/edit'

  get 'schedule/index'

  devise_for :users, :skip => [:registrations], controllers: { passwords: 'my_passwords' }
  root "application#index"
  get "/about_us", to: "application#about_us" , as: "about_us"
  get '/graduates', to: 'graduated#index', as: 'graduated'
  get '/payments-and-donations', to: 'application#payments', as: 'payments'

  get '/contact', to: 'application#contact', as: 'contact'
  get '/inscriptions', to: 'inscriptions#index', as: 'inscriptions'
  post '/inscription/create', to: 'inscriptions#create', as: "inscription_create"
  get '/circulars', to: 'circulars#index', as: 'circulars'    

  post '/contact_us', to: 'application#contact_us', as: 'contact_us'
  get '/contact_us', to: 'application#contact'
  get '/thank-you', to: 'application#thank_you_contact', as: 'thank_you'
  get '/inscriptions/thank-you', to: 'inscriptions#thank_you', as: 'inscriptions_thank_you'


  get 'circular', to: 'circular#index', as: 'ciruclar'
  get '/parents-school', to: 'application#school_parents', as: "school_parents"
  get '/history-and-appretiation-of-arts', to: 'application#history_of_arts', as: "history_of_arts"

  get '/news', to: 'news#index', as: 'news'
  get '/news/search/:term', to: 'news#search', as: 'news_search'
  get '/news/:id', to: 'news#show', as: 'news_show'
  get '/coexistence-manual', to: 'coexistence_manual#index', as: 'coexistence_manual'

  get "schedules", to: "schedules#index", as: "schedules_front"

  get '/faq', to: 'application#faq', as: 'faq'
  
  resource :passwords

  get '/change_locale/:locale', to: 'application#change_locale', as: 'change_locale'
  get "admin", to: "users#index", as: "admin"

  scope :admin do
    get "schedule/", to: "schedules#index_admin", as: "schedules_admin"
    resources :schedules
    get '/users', to: 'users#index', as: 'users'
    post '/users', to: 'users#create', as: 'users_create'
    get '/users/import', to: 'users#index_import', as: 'show_import_user'
    get '/users/new', to: 'users#new', as: 'new_user'
    get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
    get '/users/:id', to: 'users#show', as: 'user'
    patch '/users/:id', to: 'users#update', as: 'update_user'
    put '/users/:id', to: 'users#update'
    delete '/users/:id', to: 'users#destroy', as: 'destroy_user'
    post '/users/import', to: 'users#import', as: 'import_users'

    get "category_post", to: "category_posts#index_admin", as: "category_posts_admin"
    get "category_posts/new", to: "category_posts#new", as: "new_category_posts"
    get "category_posts/edit/:id", to: "category_posts#edit", as: "edit_category_posts"
    post "category_posts", to: "category_posts#create"
    patch "category_posts/update/:id", to: "category_posts#update", as: "update_category_posts"
    delete "category_posts/:id", to: "category_posts#destroy", as: "destroy_category_posts"

    get "post", to: "posts#index_admin", as: "posts_admin"
    get "posts/new", to: "posts#new", as: "new_posts"
    get "posts/edit/:slug", to: "posts#edit", as: "edit_posts"
    post "posts", to: "posts#create"
    patch "posts/update/:slug", to: "posts#update", as: "update_posts"
    delete "posts/:slug", to: "posts#destroy", as: "destroy_posts"

    get "parents-lesson", to: "parent_lessons#index_admin", as: "parents_school_lessons_admin"
    get "parents-lesson/new", to: "parent_lessons#new", as: "new_parents_school_lessons"
    get "parents-lesson/edit/:id", to: "parent_lessons#edit", as: "edit_parents_school_lessons"
    post "parents-lesson", to: "parent_lessons#create_record"
    patch "parents-lesson/update/:id", to: "parent_lessons#update", as: "update_parents_school_lessons"
    delete "parents-lesson/:id", to: "parent_lessons#destroy", as: "destroy_parents_school_lessons"

    get "history-of-arts-lesson", to: "history_lessons#index_admin", as: "history_lessons_admin"
    get "history-of-arts-lesson/new", to: "history_lessons#new", as: "new_history_lessons"
    get "history-of-arts-lesson/edit/:id", to: "history_lessons#edit", as: "edit_history_lessons"
    post "history-of-arts-lesson", to: "history_lessons#create_record", as: "history_create"
    patch "history-of-arts-lesson/update/:id", to: "history_lessons#update", as: "update_history_lessons"
    delete "history-of-arts-lesson/:id", to: "history_lessons#destroy", as: "destroy_history_lessons"

    get "home_image", to: "home_images#index_admin", as: "home_images_admin"
    get "home_images/new", to: "home_images#new", as: "new_home_images"
    get "home_images/edit/:id", to: "home_images#edit", as: "edit_home_images"
    post "home_images", to: "home_images#create"
    patch "home_images/update/:id", to: "home_images#update", as: "update_home_images"
    delete "home_images/:id", to: "home_images#destroy", as: "destroy_home_images"
    patch "home_images/change_status/:id", to: "home_images#change_status", as: "change_status_home_images"

    #resources :setups
    get 'setup', to: "setups#edit", as: "edit_setup"
    patch 'setup', to: "setups#update", as: "setup_update"
    post 'setup', to: "setups#edit", as: "setup"
    
    get "circulars", to: "circulars#index_admin", as: 'circulars_admin'
    get "circulars/new", to: "circulars#new_admin", as: "create_circular"
    get "circulars/:id/edit", to: "circulars#edit_admin", as: "edit_circular"
    patch "circulars/:id", to: "circulars#update", as: "circulars_update"
    post "circulars", to: "circulars#create", as: "circulars_create"

  end

  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false, unless: "/admin/*path"

end

app/models/circular.rb
class Circular < ApplicationRecord
  resourcify
end

app/controllers/circulars_controller.rb
class CircularsController < ApplicationController 
    before_action :authenticate_user!
    load_and_authorize_resource
    layout 'admin', only: [:index_admin, :new_admin, :edit_admin]
    before_action :find_circular, only: [:edit_admin, :update]
    before_action :find_all_circulars, only: [:index, :index_admin]

    def index_admin
    end
    
    def new_admin
        @circular = Circular.new
    end
    
    def index
    end

    def create
        @circular = Circular.new(circular_params)
        puts "******"
        puts @circular
        if @circular.valid?
            @circular.save
            redirect_to circulars_admin_path
        end
    end

    def edit_admin        
    end

    def update
        @circular.update(circular_params)
        redirect_to circulars_admin_path
    end

    private
        def circular_params
            params.require(:circular).permit(:date, :title, :content, :content_en, :title_en)
        end

        def find_circular
            @circular = Circular.find(params[:id])
        end

        def find_all_circulars
            @circulars = Circular.all
        end
end

app/helpers/circular_helper.rb
module CircularHelper
end

app/helpers/circulars_helper.rb
module CircularsHelper
end

app/views/circulars/_circular_card.html.erb
<% @circulars.each_with_index do |circular, index| %>
    <div class="panel">
        <a data-toggle="collapse" class="collapsed" data-parent="#accordion" href='<%= "#collapse#{index}" %>'>
            <div class="panel-heading">
                <h4 class="panel-title">
                    <span class="opened">-</span>
                    <span class="closed">+</span>
                    Circular: <%= l circular.date, format: :circulars %>, 
                    <% if I18n.locale == :es %>
                        <%= circular.title %>
                    <% else %>
                        <%= circular.title_en %>
                    <% end %>
                </h4>
            </div>
        </a>    
        <div id='<%= "collapse#{index}" %>' class="panel-collapse collapse">
            <div class="panel-body">
                <% if I18n.locale == :es %>
                    <p><%= circular.content %></p>
                <% else %>
                    <p><%= circular.content_en %></p>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

app/views/circulars/_form_circulars.html.erb
<%= form_for @circular, url: url, id: 'circular-form', method: method  do |f| %>
    <div class="form-group">
        <label for="exampleInputEmail1">Fecha de la circular</label>
        <%= f.date_field :date, placeholder: 'Fecha de la circular', type: 'date', class: 'form-control', required: true %>
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Titulo de la circular (Español)</label>
        <%= f.text_field :title, placeholder: 'Titulo de la circular', class: 'form-control', required: true %>
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Titulo de la circular (Ingles)</label>
        <%= f.text_field :title_en, placeholder: 'Titulo de la circular', class: 'form-control', required: true %>
    </div>

    <div class="form-group">
        <label for="exampleInputPassword1">Contenido de la circular (Español)</label>
        <%= f.text_area :content, placeholder: 'Contenido de la circular', rows: 5, class: 'form-control h-100' %>
    </div>
    
    <div class="form-group">
        <label for="exampleInputPassword1">Contenido de la circular (Ingles)</label>
        <%= f.text_area :content_en, placeholder: 'Contenido de la circular', rows: 5, class: 'form-control h-100' %>
    </div>
    <%= f.submit 'Crear', class: 'btn btn-success mr-2', type: 'submit' %>
    <%= submit_tag("Limpiar", { :name => 'reset', :id => 'reset_button', :type => "reset", :class => 'btn btn-light' }) %>
<% end %>

app/views/circulars/_layout_form.html.erb
<div class="row">
    <div class="col-12 col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <%= yield %>
            </div>
        </div>
    </div>
</div>

app/views/circulars/edit_admin.html.erb
<%= render :layout => 'layout_form' do %>
    <h4 class="card-title">Editar circular</h4>
    <%= render "form_circulars", circular: @circular, url: circulars_update_path, method: 'patch' %>
<% end %>

app/views/circulars/index.html.erb
<%= render partial: 'application/navbar' %>
<section id="our-graduates" class="circulars">
    <div class="title-container">
        <div class="row">
            <div class="col">
                <div class="title-section text-center">
                    <h2><%= t("circulars.title") %></h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container pb96 pt96 pb-xs-32">
        <div class="row">
            <div class="col">
                <div class="title-section subtitle-section text-center">
                    <h2 class="white-section"><%= t("circulars.dontMiss") %></h2>
                    <h6 class="subtitle-sm"><%= t("circulars.text") %></h6>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row content">
                <div class="col-xs-12 col-md-8 col-md-offset-2">
                    <div id="accordion" class="panel-group accordion-bootstrap">
                        <%= render "circular_card", circulars: @circulars %>
                        
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
                    <h2 class="white-section contactus">
                        <%= t("circulars.uHaveQ") %> <%= link_to contact_path do %><span><%=t('circulars.contactus')%></span><% end %>
                    </h2>
                </div>
            </div>
        </div>
    </div>
</section>
<%= render partial: 'application/footer' %>

app/views/circulars/index_admin.html.erb
<div class="row">
    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body text-center">
                <%= link_to create_circular_path do %>
                <button class="btn btn-info">
                    Crear circular
                </button>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Listado de circulares</h4>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Fecha</th>
                                <th>Titulo (ES)</th>
                                <th>Titulo (EN)</th>
                                <th>Contenido (ES)</th>
                                <th>Contenido (EN)</th>
                                <th>Creada</th>
                                <th>Editar</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% if @circulars.length > 0 %>
                                <% @circulars.each_with_index do |circular, index| %>
                                <tr>
                                    <td><%= indexplus = index + 1 %></td>
                                    <td><%= circular.date.strftime("%A %B/%d/%Y") %></td>
                                    <td><%= circular.title %></td>
                                    <td><%= circular.title_en %></td>
                                    <td><%= circular.content %></td>
                                    <td><%= circular.content_en %></td>
                                    <td><%= circular.created_at.strftime("%F") %></td>
                                    <td class="text-center">
                                        <%= link_to edit_circular_path(circular) do%>
                                        <%= fa_icon "edit" %>
                                        <% end %>
                                    </td>
                                </tr>
                                <% end %>
                            <% else %>
                            <tr>
                                <td colspan="8" class="text-center text-info">
                                    <h3 class="mt-4">
                                        No hay circulares creadas en este momento
                                    </h3>
                                    <%= link_to create_circular_path do%>
                                    <button class="btn btn-success">
                                        Crear
                                    </button>
                                    <% end %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
    
            </div>
        </div>
    </div>
</div>

app/views/circulars/new_admin.html.erb
<%= render :layout => 'layout_form' do %>
    <h4 class="card-title">Crear circular</h4>  
    <%= render "form_circulars", circular: @circular, url: circulars_create_path, method: 'post' %>
<% end %>